### ISSUE TITLE
Popcorn Beneficiaries Landing (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#10]
## Objective/Goal
We are coding the layout of the Popcorn Beneficiaries landing page here. This ticket includes the delivery of the hero image feature, the "Learn how it works" expandable modal, the title "Eligible Beneficiaries At A Glance", filter dropdown, the layout for cards, and the "See More" button. The cards, the footer, and the top nav will be coming from different tickets therefore this page has three dependencies. 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 7.26.01 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/35e41047-7422-4884-8067-176801afeedc)

**Comment by anthonymartin** [comment]
* filter functionality will not be implemented yet because the current json application spec does not include category metadata which filter would depend on

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/10?planning-poker) with ZenHub @bhanusanghi @ecmendenhall @leomarlo @thenerdcat

**Comment by Ajiva-D** [comment]
@FanFanDAO https://github.com/popcorndao/sweet-caramel/pull/624

**Comment by FanFanDAO** [comment]
@Ajiva-D Cards under "Eligible Beneficiaries At A Glance" should have the same animation as the yellow panel on popcorndao.finance. We had previously talked about this.

**Comment by FanFanDAO** [comment]
@Ajiva-D "See More" Button needs to have a hover state.
Let's use the same hover state as the "Connect Wallet" button: https://popcorndao.finance/ethereum

Also, button is off here:
![Screen Shot 2022-06-14 at 1.20.36 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/addac5d7-c00c-4392-b5c6-22886851695d)

**Comment by FanFanDAO** [comment]
@Ajiva-D "See More" Button needs to have a hover state.
Let's use the same hover state as the "Connect Wallet" button: https://popcorndao.finance/ethereum

Also, button is off here:
![Screen Shot 2022-06-14 at 1.20.36 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/addac5d7-c00c-4392-b5c6-22886851695d)

**Comment by Ajiva-D** [comment]
See more hover fixed here @FanFanDAO https://deploy-preview-854--popcorn-grants.netlify.app/

**Comment by FanFanDAO** [comment]
@Ajiva-D We need the card animation for all cards under the "Eligible Beneficiaries At A Glance" You can reference the card animation on the landing of popcorndao.finance

**Comment by Ajiva-D** [comment]
@FanFanDAO the card animation has been done but you won't be able to see it cos the page is not fetching the eligible beneficiaries from the contract. I'll have to show you on my local host
