### ISSUE TITLE
Card for Eligible Beneficiary (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#11]
## Objective/Goal
This ticket requires the card for the eligible beneficiary to be coded. It contains the image, title, and a short paragraph. The card should have an animation to size up just like how we did it for the cards on the SC landing page. Please refer to the reference image below on design. 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Hover-over animation is needed just like how we did on the SC landing
- Clean, lean, and organized code practices
- Spacings, colors, shadow, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 7.32.28 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/28f703da-7e71-4ac8-b964-6c63ba12e43f)

**Comment by RedVeil** [comment]
https://github.com/popcorndao/sweet-caramel/pull/618
