### ISSUE TITLE
Eligible Beneficiaries Landing (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#23]
## Objective/Goal
We are coding the layout of the Eligible Beneficiaries landing page here. This ticket includes the delivery of the page title, the subtitle, the filter for categories, the layout for cards, the "See More" button, and the empty state with a placeholder image for when there are no Eligible Beneficiaries. The cards, the footer, and the top nav will be coming from different tickets therefore this page has three dependencies. 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 8.45.51 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/5f6a1bd5-43dc-43f5-8cd4-04ccf508d30e)
![Screen Shot 2022-02-10 at 8.52.50 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f11b0b65-69a9-4451-8823-2049dee93195)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/23?planning-poker) with ZenHub @Ajiva-D @arne-z @bhanusanghi @ecmendenhall @leomarlo @RedVeil
