### ISSUE TITLE
Apply now Landing (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#25]
## Objective/Goal
We are coding the layout of the Apply Now landing page here. All elements except the top nav, the footer should be included in the deliverable. The final copies will come from another ticket and therefore this page has a total of three dependencies. Please refer to the reference image for layout and design.

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 9.04.40 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/60ac8a1c-3448-4f49-9893-2610bdb400d1)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/25?planning-poker) with ZenHub @ecmendenhall @leomarlo @RedVeil

**Comment by FanFanDAO** [comment]
@arne-z do you have the PR?

**Comment by Ajiva-D** [comment]
@FanFanDAO I have requested you as a reviewer on all the PRs

**Comment by FanFanDAO** [comment]
@Ajiva-D We need to update the copy here:

How can my organization qualify as a beneficiary?
To be considered for a grant, your organization must submit an application that meets two criteria:

A majority of votes must be cast in favor of the application.
The organization must address Popcorn's areas of focus (education, environment, open source).
Does my organization need POP tokens?
An organization may apply for eligible beneficiary status by purchasing the required 2000 POP tokens or contacting the Popcorn Foundation for a free nomination.

What else is needed to complete the application?
Supplementary application materials, such as a mission statement, proof of address ownership, photos, links to social media accounts, and impact reports, are required.

**Comment by FanFanDAO** [comment]
Still unresolved! @Ajiva-D 
![Screen Shot 2022-06-14 at 12.03.10 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/eb16c966-dee6-4f48-b1b2-1fd07ba1fd45)

**Comment by FanFanDAO** [comment]
@Ajiva-D "Create Proposal" button hover state missing.
Please refer to button page in our DS: https://www.figma.com/file/5bmpYjaYkpoefISS9afbHc/Design-System?node-id=6502%3A4688

**Comment by FanFanDAO** [comment]
@Ajiva-D Let's adjust the hover and connected wallet treatment just like what we have on the live site of popcorndao.finance. I know the DS doesn't reflect the same, and in this case, I think the result on the live site looks good so I will have the designer update this onto our current design system as well. Let me know if there is anything unclear. :)

**Comment by FanFanDAO** [comment]
@Ajiva-D "Apply Now" was not changed?
![Screen Shot 2022-06-14 at 2.58.37 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/5efdf532-2b8d-46bb-a286-f554664429a3)

**Comment by Ajiva-D** [comment]
https://deploy-preview-843--popcorn-grants.netlify.app/ @FanFanDAO this review contains every fix here apart from the ones for the Steps Apply flow and Connect Wallet on the top nav

**Comment by FanFanDAO** [comment]
@Ajiva-D can you download and use the highest quality of this image?
 https://unsplash.com/photos/3Rn2EjoAC1g
