### ISSUE TITLE
Beneficiary Application Flow - Step 1 General Information (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#28]
## Objective/Goal
We are coding the layout and form fields of the Beneficiary Application flow for Step 1. The top nav and the footer will be coming from different tickets therefore this ticket has two dependencies. 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Next button should be inactive until the user filled in all the info
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-15 at 6.14.26 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/5f8bf807-56c1-439d-8ac7-264233deceaf)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/28?planning-poker) with ZenHub @ecmendenhall @leomarlo @RedVeil

**Comment by RedVeil** [comment]
- During the process data should be stored in local storage (CIDs for IPFS things)
- Uploads need to be configured for IPFS
- Split the process into steps rather than using multiple pages
- Current step/data in local storage
- Steps should be an enum
- We should validate that the ethereum address is a valid address and that the email is valid

**Comment by anthonymartin** [comment]
@RedVeil @Ajiva-D - the implmentation already exists for this and should be working in the `packages/grants` dir. it's just the styling that needs updating

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/660
