### ISSUE TITLE
Beneficiary Application Flow - Step 2 Provide a URL as a proof (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#29]
## Objective/Goal
We are coding the layout and form fields of the Beneficiary Application flow for Step 2. The top nav and the footer will be coming from different tickets therefore this ticket has two dependencies. 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Next button should be inactive until the user filled in with a valid URL
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 9.29.51 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f804abb5-4e16-4df9-a31e-8b0db3f08af9)

**Comment by FanFanDAO** [comment]
@arne-z do you have the PR?

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/662
