### ISSUE TITLE
Beneficiary Application Flow - Step 3 Upload Impact Reports (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#30]
## Objective/Goal
We are coding the layout and form fields of the Beneficiary Application flow for Step 3. The top nav and the footer will be coming from different tickets therefore this ticket has two dependencies. 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Next button should be inactive until the user filled in with a valid URL
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 9.38.30 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b111255f-7059-4800-bcbe-c8a3e6d22650)
![Screen Shot 2022-02-10 at 9.38.41 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c61b7eb9-f790-4219-a2e5-73a26eecd144)

**Comment by anthonymartin** [comment]
* This step is optional and language should be updated accordingly

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/30?planning-poker) with ZenHub @arne-z @ecmendenhall @leomarlo @RedVeil

**Comment by RedVeil** [comment]
- Impact reports are uploaded to IPFS immediately and the CIDs are stored
- Upload progress bars are not mandatory as part of this package

**Comment by FanFanDAO** [comment]
@arne-z do you have the PR?

**Comment by FanFanDAO** [comment]
@Ajiva-D Missing I think it is not clear for the user how to upload files. We should change the text "No Files Selected" to "Upload Files". This is a treatment alternative without going with the original Figma design. 
![Screen Shot 2022-06-14 at 3.10.54 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c8237467-2a83-45c7-a9f3-27f2feb2a561)

**Comment by Ajiva-D** [comment]
link is in step 4
