### ISSUE TITLE
Beneficiary Application Flow - Step 4 Upload Visual Content (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#31]
## Objective/Goal
We are coding the layout and form fields of the Beneficiary Application flow for Step 4. The drag and drop function should be made possible here. Please pay attention to the reference images below where it shows you the different states during the image upload process. The top nav and the footer will be coming from different tickets therefore this ticket has two dependencies. 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Drag and drop image functions should be made possible
- Next button should be inactive until the user uploaded at least one image.
- One Progress bar per file that is being uploaded in a list view
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 9.41.21 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/45385a50-de1c-4dd1-926e-665b382f8225)
![Screen Shot 2022-02-10 at 9.41.32 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e4ea708e-31ae-4b15-92b8-8fdad75ddaa8)
![Screen Shot 2022-02-10 at 9.41.43 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ece0ef7a-0468-43f4-924a-9bf34393cf71)
![Screen Shot 2022-02-10 at 9.42.11 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3f8d4635-bf29-4675-805d-111df11d42fd)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/31?planning-poker) with ZenHub @arne-z @ecmendenhall @leomarlo @RedVeil

**Comment by RedVeil** [comment]
- Images are uploaded to IPFS immediately and the CIDs are stored
- Upload progress bars are not mandatory as part of this package
- Each image has a description here, which is added under the image preview once the image is uploaded.

**Comment by FanFanDAO** [comment]
@arne-z can you attach the PR?

**Comment by arne-z** [comment]
https://github.com/popcorndao/sweet-caramel/pull/664

**Comment by FanFanDAO** [comment]
@arne-z @Ajiva-D It is not showing.
![Screen Shot 2022-05-19 at 5.01.04 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ddb5cd78-fa59-4d09-92c7-e0237275e825)

**Comment by FanFanDAO** [comment]
@arne-z @Ajiva-D It is not showing.
![Screen Shot 2022-05-19 at 5.01.04 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ddb5cd78-fa59-4d09-92c7-e0237275e825)

**Comment by FanFanDAO** [comment]
@Ajiva-D Please let me know when the upload function is ready and I will try to review it again. :) Thanks for getting the page to work and addressing the previous comment where the page does not display.

**Comment by FanFanDAO** [comment]
@Ajiva-D Uploaded image is not showing up.
![Screen Shot 2022-06-14 at 3.15.16 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/87d287ae-bd15-4f4a-a539-78cfd2b13759)

**Comment by FanFanDAO** [comment]
@Ajiva-D I have a small mp4, but it can not be uploaded somehow. The file is grayed out. 
![Screen Shot 2022-06-14 at 3.26.03 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a331297c-c032-47d9-9792-a84d6ca15406)

**Comment by Ajiva-D** [comment]
@FanFanDAO all the updates for this ticket and the ones for step 3 and step 1 tickets are in this deploy preview, https://deploy-preview-845--popcorn-grants.netlify.app/
