### ISSUE TITLE
About - Profile Detail Page without voting modal (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#32]
## Objective/Goal
We are coding the layout of the Profile Detail Page under the About tab. This version is without the voting modal and is for any eligible beneficiary. The top nav and the footer will be coming from different tickets therefore this ticket has two dependencies. 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 9.49.26 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/79def947-ea46-43ae-8a67-47b43ded9757)

**Comment by Ajiva-D** [comment]
@FanFanDAO 
![Screenshot 2022-07-08 at 10-20-35 Popcorn - DeFi for the People.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/e5681c03-ecc5-4f50-a3bf-e9bbf029ebf2)

**Comment by Ajiva-D** [comment]
@FanFanDAO 
![Screenshot 2022-07-08 at 10-20-35 Popcorn - DeFi for the People.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/cdd05468-1f00-4977-9450-94b42b0c1d66)

**Comment by Ajiva-D** [comment]
Updated now @FanFanDAO 
![Screenshot 2022-07-11 at 14-02-22 Popcorn - DeFi for the People.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/2e171c21-8f83-47f4-8d40-c9247f91e994)
