### ISSUE TITLE
Gallery - Profile Detail Page without voting modal (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#33]
## Objective/Goal
We are coding the layout and the components of the Profile Detail Page under the Gallery tab. This version is without the voting modal and is for any eligible beneficiary. Each image has a social share icon on the image. When the user clicks on the share icon social icons should be seen on top of the image. To understand this better please look at the image reference below. The top nav and the footer will be coming from different tickets therefore this ticket has two dependencies. 

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 9.53.52 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/67938773-839a-4667-aa18-a30c191594b5)

**Comment by Ajiva-D** [comment]
@FanFanDAO 
![Screenshot 2022-07-11 at 14.21.27.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/dac595ed-679d-4b98-9d52-5d8c78b48b92)

**Comment by Ajiva-D** [comment]
![Screenshot 2022-07-11 at 14.26.37.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/1b9428ab-a4d5-4852-b384-ee9bbd1bfa3b)

**Comment by FanFanDAO** [comment]
@Ajiva-D can you get me a screen capture at 760px and 375px?
