### ISSUE TITLE
01 Popover for Accept Application - Profile Detail Page (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#44]
## Objective/Goal
This popover shows up when the user clicked the "Accept" button within the Vote modal. It informs the user about his/her action.

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Make sure we follow the same popover styling we had created for under SC aside from the new functionalities and info.
- Clean, lean, and organized code practices
- Spacings, colors, shadow, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 11.27.03 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/051f52b8-7006-4df1-a377-910a6f9d0579)

**Comment by Ajiva-D** [comment]
@FanFanDAO ![Screenshot 2022-06-30 at 13.36.37.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/20f55dd9-1df7-4909-891d-b35c2c41277c)
