### ISSUE TITLE
02 Popover confirmation on reject an application - Profile Detail Page (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#49]
## Objective/Goal
This popover shows up when the user clicked the "Reject" button from within the Reject Application popover. It is intended to provide the user with clarity on what to expect next.

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Make sure we follow the same popover styling we had created for under SC aside from the new functionalities and info.
- Clean, lean, and organized code practices
- Spacings, colors, shadow, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 11.53.27 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/bef82839-1183-4b71-a9dd-4fe7e851894c)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/49?planning-poker) with ZenHub @Ajiva-D @arne-z @bhanusanghi @ecmendenhall @leomarlo @RedVeil

**Comment by Ajiva-D** [comment]
@FanFanDAO ![Screenshot 2022-06-30 at 15.07.15.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/dcebf0af-101d-4064-bc52-38150ed85a5b)
