### ISSUE TITLE
01 Popover for Submit Application - Beneficiary Application Flow Step 4 (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#51]
## Objective/Goal
This popover shows up when the user clicked the "Finish" button upon completing the step 4 process in the Beneficiary Application flow. It informs the user about the process of locking 2000 POP and what to expect next.

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Make sure we follow the same popover styling we had created for under SC aside from the new functionalities and info.
- Clean, lean, and organized code practices
- Spacings, colors, shadow, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-03-11 at 7.37.04 AM 1.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/eb4f1684-b0c2-476b-84b7-fff6d96eff83)
![Screen Shot 2022-03-11 at 7.37.12 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a4fa6506-fd99-4eff-bc3c-e605ca5f848a)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/51?planning-poker) with ZenHub @arne-z @ecmendenhall @leomarlo @RedVeil

**Comment by RedVeil** [comment]
For now this is just visual. Need to speak with anthony to see what we do on the contract side

**Comment by FanFanDAO** [comment]
@arne-z @Ajiva-D 

Hi guys, 

In our previous experience, it was not possible to view popover with a PR. Would you guys be able to update a screenshot captured for all popovers that are done and ready to review?

**Comment by Ajiva-D** [comment]
![Screenshot 2022-05-23 at 16.25.38.png](https://images.zenhubusercontent.com/625eb6ea90b5fd165b134d8b/a8e4cd16-ac11-4365-947f-b63ef8a7d2a9)

**Comment by FanFanDAO** [comment]
Lock & Submit button doesn't work @Ajiva-D

**Comment by FanFanDAO** [comment]
@Ajiva-D Uploaded image is not showing up.
![Screen Shot 2022-06-14 at 3.15.16 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/87d287ae-bd15-4f4a-a539-78cfd2b13759)

**Comment by FanFanDAO** [comment]
@Ajiva-D "Lock & Submit" button doesn't work. Not sure if I had to have the 2000 POP in the POP Testing Metamask account to get through it. 

@RedVeil  If I need 2000 POP, can you send some POP to the POP Testing account?
0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

**Comment by Ajiva-D** [comment]
https://deploy-preview-843--popcorn-grants.netlify.app/apply/form @FanFanDAO
