### ISSUE TITLE
02 Popover with Congrats message - Beneficiary Application Flow Step 4 (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#52]
## Objective/Goal
This popover shows up when the user clicked the "Submit" button from within the popover for Submit Application. It informs the user on what to expect next.

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Make sure we follow the same popover styling we had created for under SC aside from the new functionalities and info.
- Clicking "Done" links back to application flow home.
- Clean, lean, and organized code practices
- Spacings, colors, shadow, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-11 at 12.12.59 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b85cbcef-9f3e-4dac-839c-b03a8899e0e5)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/52?planning-poker) with ZenHub @arne-z @ecmendenhall @leomarlo @RedVeil

**Comment by FanFanDAO** [comment]
@Ajiva-D This review is blocked a comment from ticket: #51
