### ISSUE TITLE
Copies - Learn How It Works

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#53]
## To-do
Let's update the copies provided in the comment box below from Lili. Please use the reference image below to guide you on the locations of the copies.

## Deliverable
- accurate text updates

## Design Reference
![Screen Shot 2022-02-11 at 12.16.01 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f22fbcbd-cdef-4bf4-b77c-dc45335e4352)

**Comment by lilivdal** [comment]
https://docs.google.com/document/d/1I3B2yM7Vn9NEEVaEphfUH1Y9-qfenRQ9XLgd87lmE74/edit

**Comment by Ajiva-D** [comment]
@FanFanDAO this page hasn't been worked on yet

**Comment by FanFanDAO** [comment]
All good. I have combined this ticket to the landing page ticket associated with it. I will close this ticket now.
