### ISSUE TITLE
Copies/Content Adjustment - Apply Now Landing

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#54]
## To-do
We need to think about the copies here or rethink the best info to incorporate into the application flow.
I saw this questionnaire and thought some questions were good to ask; however, this is not part of the initial application criteria. We need to decide and factor into the most needed info that would prove the legitimacy of an organization and how they can provide the best information to attract the user's attention within a reasonable length so that this process is not too long and hard to complete.

## Deliverable
- a text doc with final content 

## Sign off needed by leads
- needs Anthony to agree on this

## Design Reference
![Screen Shot 2022-02-11 at 12.20.42 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d72f3f72-b086-4fc9-8c24-c1512bf7114c)

**Comment by lilivdal** [comment]
https://docs.google.com/document/d/1I3B2yM7Vn9NEEVaEphfUH1Y9-qfenRQ9XLgd87lmE74/edit

**Comment by FanFanDAO** [comment]
@anthonymartin Here is Lili's wording for part of the BenGov copies after looking at the prototype. I quite like the language here since it is easier to understand but let me know. Link to more copies in BenGov: https://docs.google.com/document/d/1I3B2yM7Vn9NEEVaEphfUH1Y9-qfenRQ9XLgd87lmE74/edit

## Copy related to this ticket
How can my organization qualify as a beneficiary?
To be considered for a grant, your organization must submit a Beneficiary Nomination Proposal (BNP) that meets two criteria: 
1. A majority of votes must be cast in favor of the proposal. 
2. At least 10% of the available supply of governance tokens must be used to vote for your organization's acceptance as a beneficiary.

Does my organization need POP tokens?
An organization may apply for eligible beneficiary status by purchasing the required 2000 POP tokens or contacting the Popcorn Foundation for a free nomination.

What else is needed to complete the application?
Supplementary application materials, such as a mission statement, proof of address ownership, photos, links to social media accounts, and impact reports, are required.
