### ISSUE TITLE
Update sitemap for Popcorn Beneficiaries

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#56]
## To-do
Let's update this sitemap with other pages we had created. 

## Source
https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=5314%3A77483

## Current State
![Screen Shot 2022-02-14 at 4.13.45 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b52e7f32-2254-4da5-b0e4-617fe2e3da8c)

**Comment by annisharafi** [comment]
updated 
![image.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/5650b534-fd93-495d-9e12-b0a7b4db23bf)
