### ISSUE TITLE
Profile Edit Functions (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#59]
## Source File
- https://www.figma.com/file/oBAkexkf8kzzWE5A9ZCpAa/BenGov?node-id=5532%3A64265

## Key Design Requirements
- On brand and aligned with our Design System 1.0
- UX and its entire flow should be catered to both mobile and desktop at all widths and sizes
- Make sure you are thinking hover state, on-press state, and inactive state at all times when applicable

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Design new screens and update all related screens. 
(*Make sure you don't mass up the clickable prototype)
![Screen Shot 2022-03-09 at 4.29.25 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8dc48221-99fa-4fc3-86ad-291ac5f402ed)
![Screen Shot 2022-03-09 at 4.29.41 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9b35dbc5-101b-491d-8995-923c06539a51)

## UX Reference
Icon
![Screen-Shot-2022-03-09-at-4.27.16-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9a79b7c8-ee02-4cf0-86cc-f7bcf0ac2762)

Popover Type 1
![Screen Shot 2022-03-09 at 4.27.55 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/441dfd6c-233e-4599-8eb7-231b99cd0fdf)

Popover Type 2
![Screen Shot 2022-03-09 at 4.27.33 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/039d12f1-08c4-4113-bf9b-0c763beba999)

**Comment by FanFanDAO** [comment]
@anthonymartin, a video intro has been made: https://www.notion.so/popcorn-network/Beneficiary-Profile-Page-ed26c45e9a2b44eeb74e30bc1eb9b9cf

**Comment by anthonymartin** [comment]
@FanFanDAO - I've reviewed the video - it looks good to me!
