### ISSUE TITLE
Update copies on Popcorn Beneficiary

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#68]
## To-do
We need to update all text indicated in the document link below. Please make sure that all similar screens are updated and that the prototype links are not disturbed.

## Link
https://docs.google.com/document/d/17_Lv4uHfpSEYFDdc5yHyNsjGp4QsJTJoUN19xIigfy8/edit

**Comment by mishraashish006** [comment]
1.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/f8820f5f-00f3-4794-9e1f-6b8e64891fa4)

2.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/a11ce1b7-be57-47ca-ac86-91f5c295299b)

3.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/f179d1b5-702a-4867-8c9e-60054d96f1c4)

4.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/d001301d-fcfb-4483-bc03-009010baff01)

5.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/26a5dda0-48d7-43da-bf9c-9b29d1b446e3)

6.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/1b0eadb9-ba4f-4a42-81fe-b01f8b1a100a)

7.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/45c64cb5-affc-4e99-9a7c-25f66977cb55)

9.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/435c7e3a-ed09-4d0e-a468-31fa3640041f)

10.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/b1d31d4d-1d8f-4ed0-8bcb-88b77cddd9d0)

11.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/60a73ccf-697b-4d7b-823e-fd6b70be479e)

13 & 14.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/6ad8c5dd-567e-442b-934e-e90f3c1c38da)

15.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/b90ecdd6-c463-4f86-ad5d-570d76551a7a)

17.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/55ff6c3b-cbf6-4610-a4ef-054d7f587d1b)

19.![image.png](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/db997e8d-8fea-4697-b115-5cd59b3d335e)
