### ISSUE TITLE
Popover for profile sharing - Profile Detail Page

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#74]
## Description
The user should be able to share this profile with friends and family through social media. This popover gets triggered when the user clicked on the "Share" button in the lower-left corner of the feature image from within the Profile detail Page. 
​
## Specific Acceptance Criteria
- All links should work normally upon clicking
- Function to trigger email sharing. It should cause an email formating window to show up
- Function for link sharing, essentially, a link is automatically copied and ideally shorten

## Resources
https://www.figma.com/file/oBAkexkf8kzzWE5A9ZCpAa/BenGov?node-id=5532%3A64265

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-07-11 at 3.32.20 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d234b3f4-baa3-4840-a97c-3f2ee093bb22)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/74?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @ecmendenhall @K-G-J @RedVeil
