### ISSUE TITLE
Top Nav (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#8]
## Objective/Goal
The top nav here consists of a dropdown menu which we already had the code for from another site. Both the top nav and the dropdown menu should be coded under this ticket. For more details, please refer to the reference images below.

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-10 at 7.04.28 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/6381ffc4-a022-44c4-8c78-e98c63ff2efb)
![Screen Shot 2022-02-10 at 7.04.51 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/0f764afe-bffa-47ef-827e-e72240819017)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/8?planning-poker) with ZenHub @bhanusanghi @ecmendenhall @leomarlo @thenerdcat

**Comment by Ajiva-D** [comment]
@FanFanDAO from what I can see, the Connect wallet button is styled correctly based on the design system for buttons on figma and the popcorndao.finance website to0. Please if I'm missing something, let me know.

**Comment by Ajiva-D** [comment]
@FanFanDAO deploy preview for this ticket https://deploy-preview-844--popcorn-grants.netlify.app/

**Comment by FanFanDAO** [comment]
@Ajiva-D There is a color difference and font-weight difference.
BenGov button:
![Screen Shot 2022-06-16 at 2.44.16 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1a6c7139-d8d5-48a1-9c33-078b8ddb69d9)
The live button on our current website:
![Screen Shot 2022-06-16 at 2.44.06 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/6866bb71-bf65-461c-b9f6-f3254ac4988c)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://deploy-preview-844--popcorn-grants.netlify.app/

**Comment by FanFanDAO** [comment]
Comment from David "They have the same boldness codewise. You remember that for some reason the boldness isn't accurate on your screen. I suspect this is due to the deployment and it's something we'll look at when we want to release"

**Comment by FanFanDAO** [comment]
@Ajiva-D We need to update the top nav for the MVP:
- Vote Now dropdown would just show Beneficiary Application
- Eligible Beneficiaries

Mobile: make sure the top nav is updated with the recent top nav you had done for the .finance website.

**Comment by Ajiva-D** [comment]
@FanFanDAO https://deploy-preview-933--sweet-caramel.netlify.app/

**Comment by FanFanDAO** [comment]
@Ajiva-D so there is no way to modify and adjust the top and bottom spacings for this plugin? The default network should be ethereum. Maybe you want to reorder the menu?

**Comment by FanFanDAO** [comment]
@anthonymartin  We will rework all current Grants screens based on the new rebrand screens. Therefore, this ticket should be paused for the moment. 

@Ajiva-D, please follow the new Grant screen design process and status in the Figma: https://www.figma.com/file/oBAkexkf8kzzWE5A9ZCpAa/Grants?node-id=5532%3A64265

It is currently in progress but does communicate closely with Annisha on updates.
