### ISSUE TITLE
Copy update - How it works (BenGov Landing)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#82]
## To-do
Update the below text within the How-It-Works expandable from within the BenGov main landing page

## Resource
https://docs.google.com/document/d/1I3B2yM7Vn9NEEVaEphfUH1Y9-qfenRQ9XLgd87lmE74/edit
Nominate an Organization
An organization wishing to apply for eligible beneficiary status may acquire the requisite number of 2000 $POP tokens to raise a Beneficiary Nomination Proposal. Alternatively they may reach out to the Popcorn Foundation to seek a nomination at no cost.

Vote
In order to accept eligible beneficiaries, we use a two-phase binary voting process (Accept or Reject). Following these two voting rounds, a voice credit allocation voting process will be held in the Grant Rounds section of our website.

Organization get funded
Grants are awarded to a set number of top-ranking beneficiaries as voted on by the $POP-token holders.

**Comment by Ajiva-D** [comment]
https://deploy-preview-852--popcorn-grants.netlify.app/ @FanFanDAO

**Comment by Ajiva-D** [comment]
updated @FanFanDAO https://deploy-preview-852--popcorn-grants.netlify.app
