### ISSUE TITLE
Copy Update - List of Requirements (Apply Now Page)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#83]
## Description
Let's update copy for the List of Requirements section from within the Apply Now Page for BenGov
​
## Specific Acceptance Criteria
- Please style text just like our reference image below
​
## Resources
Copy: https://docs.google.com/document/d/1I3B2yM7Vn9NEEVaEphfUH1Y9-qfenRQ9XLgd87lmE74/edit

### General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-06-21 at 2.37.49 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e4558e83-81f6-45d8-ad7e-19c12edb4a3b)

**Comment by Ajiva-D** [comment]
@FanFanDAO https://deploy-preview-923--popcorn-grants.netlify.app/apply
