### ISSUE TITLE
Footer (Desktop)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/beneficiaries#9]
## Objective/Goal
We have a similar design coded for the footer on popcorn.network website. In this ticket, we need to take the code we already have and update the right links. Please look at the reference images below.

## Source File
- https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-Beneficiaries?node-id=5661%3A178612

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and do communicate if there are any questions through discord or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
To-Be-Provided.

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/beneficiaries/9?planning-poker) with ZenHub @bhanusanghi @ecmendenhall @leomarlo @thenerdcat

**Comment by FanFanDAO** [comment]
@Ajiva-D Can we fix the styling here and make sure it doesn't float on top of any modal or cards on a page when scrolling down?
![Screen Shot 2022-06-16 at 2.48.41 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3004e9be-e5a7-4d22-bf50-f9452b98175c)

This is from our Figma file:
![Screen Shot 2022-06-16 at 3.16.35 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d101ca94-5995-4ddd-b23a-a94ca267b607)

**Comment by Ajiva-D** [comment]
@FanFanDAO the float on top has been fixed in this preview https://deploy-preview-843--popcorn-grants.netlify.app/apply/form
It's not very clear where you want us to apply extra padding and why.

**Comment by FanFanDAO** [comment]
@Ajiva-D This is from the above PR. Can you see that the right padding is not even?
![Screen Shot 2022-06-20 at 12.40.40 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3a6b5f6b-f424-4db3-b0cc-d619c032a1ab)
We should do this:
![Screen Shot 2022-06-20 at 12.40.49 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/923d7ddd-72d5-48c9-a641-1032fcc8b429)

**Comment by Ajiva-D** [comment]
Ah, got it now

**Comment by Ajiva-D** [comment]
fixed button padding here @FanFanDAO https://deploy-preview-854--popcorn-grants.netlify.app/
